### ISSUE TITLE
Adding Bamboo support

### ISSUE THREAD

**Issue by atl-mk** [sindresorhus/is-in-ci#1]
Hey,

Would be keen to see Bamboo support, the variables are listed here: https://confluence.atlassian.com/bamboo/bamboo-variables-289277087.html

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/is-in-ci?tab=readme-ov-file#how-can-i-add-a-ci-service

> Request the CI service to include the `CI` environment variable. Most already do.

**Comment by atl-mk** [comment]
Feature request is already open, but little movement on their front. Apologies, it seems reasonable because all of their variables start with `bamboo` avoiding the likelihood of conflict which is the stated reason for divergence.
